version: 2
jobs:
  test:
    docker:
    # specify the version you desire here
    - image: circleci/node:10.4.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  build:
    deploy:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy Master to Heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
    
    build_dev:
      docker:
        - image: circleci/node:10.4.1

      steps:
        - checkout

        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-

        - run: npm install

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        deploy:
          docker:
            - image: buildpack-deps:trusty
          steps:
            - checkout
            - run:
                name: Deploy Master to Heroku
                command: |
                  git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEV_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
      - build_dev
      - deploy:
          requires:
            - test
            - build_dev
          filters:
            branches:
              only: dev
