version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run deploy!
      # - run: git checkout dev
      # - run: git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/dev-ent-mrshaw-web.git dev:master
      # - run: echo "Deployed to development server"

      deploy:
        docker:
          - image: buildpack-deps:trusty
        steps:
          - checkout
          - run: npm test
          - run:
              name: Deploy Master to Heroku
              command: |
                git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

                build:
    
    build_dev:
      docker:
        - image: circleci/node:7.10

      steps:
        - checkout

        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-

        - run: npm install

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        deploy:
          docker:
            - image: buildpack-deps:trusty
          steps:
            - checkout
            - run: npm test
            - run:
                name: Deploy Master to Heroku
                command: |
                  git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEV_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - build_dev
      - deploy:
          requires:
            - build_dev
          filters:
            branches:
              only: dev
